config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :my_threads, except: [:new] do
    resources :comments, shallow: true, only: [:create, :edit, :update, :destroy]
  end

  root 'my_threads#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :my_thread
end

app/models/my_thread.rb
class MyThread < ApplicationRecord
  belongs_to :user
  has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :my_threads
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  def create
    @my_thread = MyThread.find(params[:my_thread_id])
    @comment = @my_thread.comments.create(comment_params)
    redirect_to my_thread_path(params[:my_thread_id])
  end

  def edit
  end

  def destroy
    @comment.destroy
    redirect_to my_thread_path(@comment.my_thread_id)
  end

  def update
    if @comment.update(comment_params)
      redirect_to my_thread_path(@comment.my_thread_id)
    else
      render 'show'
    end
  end

  private
    def comment_params
      params[:comment].permit(:user_id, :body)
    end

    def set_comment
      @comment = Comment.find(params[:id])
    end

end

app/controllers/my_threads_controller.rb
class MyThreadsController < ApplicationController

  before_action :set_my_thread, only: [:show, :edit, :update, :destroy]

  def index
    @my_threads = MyThread.all
  end

  def create
    @my_thread = MyThread.create(my_thread_params)
    redirect_to my_threads_path
  end

  def show
  end

  def edit
  end

  def update
    if @my_thread.update(my_thread_params)
      redirect_to my_threads_path
    else
      render 'edit'
    end
  end

  def destroy
    @my_thread.destroy
    redirect_to my_threads_path
  end

  private
    def my_thread_params
      params.require(:my_thread).permit(:user_id, :title, :body)
    end

    def set_my_thread
      @my_thread = MyThread.find(params[:id])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/my_threads_helper.rb
module MyThreadsHelper
end

app/views/comments/edit.html.erb
  <p>Edit comment</p>
  <%= form_for @comment do |f| %>
    <%= f.hidden_field :user_id, value: 1 %>
    <%= f.text_area :body %>
    <%= f.submit %>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BoardPlus</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <%= link_to '[ログアウト]', destroy_user_session_path, method: :delete %>
    </header>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

app/views/my_threads/edit.html.erb
  <h1>Edit your thread</h1>
  <%= form_for @my_thread do |f| %>
    <%= f.hidden_field :user_id, value: 1 %>
    <p>Title</p>
    <p><%= f.text_field :title %></p>
    <p>Text</p>
    <p><%= f.text_area :body %></p>
    <%= f.submit %>
  <% end %>

app/views/my_threads/index.html.erb
  <h2>Post new thread</h2>
  <%= form_for @my_threads.new do |f| %>
    <%= f.hidden_field :user_id, value: 1 %>
    <h5>Title</h5>
    <p><%= f.text_field :title %></p>
    <h5>Text</h5>
    <p><%= f.text_area :body %></p>
    <p><%= f.submit %></p>
  <% end %>
  <h1>Threads List</h1>
  <ul>
  <% @my_threads.each do |my_thread| %>
    <%= link_to my_thread_path(my_thread.id) do %>
      <li>
        <h3><%= my_thread.title %></h3>
        <span><%= my_thread.body %></span>
      </li>
    <% end %>
  <% end %>
  </ul>

app/views/my_threads/show.html.erb
  <h1><%= @my_thread.title %></h1>
  <div><%= @my_thread.body %></div>
  <%= link_to '[戻る]', my_threads_path %>
  <%= link_to '[編集]', edit_my_thread_path(@my_thread.id) %>
  <%= link_to '[削除]', my_thread_path(@my_thread.id), method: :delete, data: { confirm: '削除しますか？' } %>
  <h2>Comments</h2>

  <ul>
  <% @my_thread.comments.each do |comment| %>
    <li>
      <%= comment.body %>
      <%= link_to '[編集]', edit_comment_path(comment.id) %>
      <%= link_to '[削除]', comment_path(comment.id), method: :delete, data: {confirm: '削除しますか？'} %>
    </li>
  <% end %>
  </ul>

  <p>Post your comment</p>
  <%= form_for [@my_thread, @my_thread.comments.build] do |f| %>
    <%= f.hidden_field :user_id, value: 1 %>
    <%= f.text_area :body %>
    <%= f.submit %>
  <% end %>